/*
 * This file was automatically generated by EvoSuite
 * Tue Sep 05 19:26:16 GMT 2017
 */

package org.araguacaima.exception.core;

import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.util.Locale;

import static org.evosuite.runtime.EvoAssertions.verifyException;
import static org.evosuite.shaded.org.mockito.Mockito.doReturn;
import static org.evosuite.shaded.org.mockito.Mockito.mock;
import static org.junit.Assert.*;

@RunWith(EvoRunner.class)
@EvoRunnerParameters(mockJVMNonDeterminism = true,
                     useVFS = true,
                     useVNET = true,
                     resetStaticState = true,
                     separateClassLoader = true,
                     useJEE = true)
public class Exceptions_ESTest extends Exceptions_ESTest_scaffolding {

    @Test(timeout = 4000)
    public void test0()
            throws Throwable {
        String string0 = Exceptions.getBundleName();
        assertEquals("exceptions.properties", string0);
    }

    @Test(timeout = 4000)
    public void test1()
            throws Throwable {
        Exception exception0 = mock(Exception.class, new ViolatedAssumptionAnswer());
        doReturn((String) null).when(exception0).getMessage();
        // Undeclared exception!
        try {
            Exceptions.handleException(exception0, (String) null);
            fail("Expecting exception: RuntimeException");

        } catch (RuntimeException e) {
            //
            // [[UNKNOWN]]
            //
            verifyException("org.araguacaima.exception.core.Exceptions", e);
        }
    }

    @Test(timeout = 4000)
    public void test2()
            throws Throwable {
        // Undeclared exception!
        try {
            Exceptions.handleException((Exception) null, "TESTMESSAGE");
            fail("Expecting exception: NullPointerException");

        } catch (NullPointerException e) {
            //
            // no message in exception (getMessage() returned null)
            //
            verifyException("org.araguacaima.exception.core.TechnicalException", e);
        }
    }

    @Test(timeout = 4000)
    public void test3()
            throws Throwable {
        Locale locale0 = Locale.KOREAN;
        String string0 = Exceptions.getMessage("", locale0);
        assertEquals("[[]]", string0);
    }

    @Test(timeout = 4000)
    public void test4()
            throws Throwable {
        Exceptions exceptions0 = new Exceptions();
        assertEquals("exceptions.properties", exceptions0.getBundleName());
    }

    @Test(timeout = 4000)
    public void test5()
            throws Throwable {
        String string0 = Exceptions.getMessage("");
        assertEquals("[[]]", string0);
    }

    @Test(timeout = 4000)
    public void test6()
            throws Throwable {
        Exceptions.setBundleName((String) null);
        String string0 = Exceptions.getBundleName();
        assertNull(string0);
    }
}
